### PR TITLE
BLUI-3220 MobileStepper and PasswordRequirement dark theme not showing proper active/valid state color

### LINKED ISSUE #161: PasswordRequirement dark theme not showing active state
#### Describe the bug
PasswordRequirement active state does not render properly when using the dark theme.

#### What is the expected behavior?
The active state of this components should render with a color of `theme.colors.primary`

#### What are the steps to reproduce?
1. Go to login workflow
2. Click create account
4. Click through to the create password screen
5. Observe the active state of the password requirements are not updating properly

#### Screenshots or links to minimum reproduction example

Simulator Screen Shot - iPhone 12 - 2022-07-14 at 14 29 25

#### Anything else to add?

### PR DESCRIPTION
**Pull request by daileytj**
Fixes #161 / BLUI-3220 .

#### Changes proposed in this Pull Request:
- Use proper colors for MobileStepper and RequirementCheck active/valid state when using dark theme

#### Screenshots:
Left: Before | Right: After
Screen Shot 2022-07-14 at 3 15 29 PM

#### To Test:
- `git clone git@github.com:brightlayer-ui/react-native-workflows.git`
- `git checkout feature/BLUI-3220-mobile-stepper-pw-dark-theme-bug`
- update `example/App.tsx` line 262 to use the dark theme `{BLUIThemes.blueDark}`
- yarn start:example
- go to create account
- observe dot stepper showing the active state of which screen you are on
- step through to create password
- update password accordingly and observe the PasswordRequirements are being checked off with the proper color

### CODE REVIEW

**Comment by ektasawant** [comment]
Stepper and active dots working fine.
Screenshot 2022-07-15 at 11 48 38 AM

There is missing translation. I believed we have already fixed it.
Screenshot 2022-07-15 at 11 48 19 AM

File: login-workflow/src/screens/InviteRegistrationPager.tsx [hunk 1]
```diff
@@ -521,9 +521,7 @@ export const InviteRegistrationPager: React.FC<InviteRegistrationPagerProps> = (
                     styles={{ root: [containerStyles.topBorder, { flex: 0 }] }}
                     steps={RegistrationPages.length}
                     activeStep={currentPage}
-                    activeColor={
-                        (theme.dark ? theme.colors.actionPalette.active : theme.colors.primary) || theme.colors.primary
-                    }
+                    activeColor={theme.colors.primary}
```
Comment (joebochill) [inline login-workflow/src/screens/InviteRegistrationPager.tsx:524]: This does what you want, but it's not where the root fix should be. We shouldn't have to override the default activeColor for this to look right— we should fix the default behavior in the component and then remove the `activeColor` prop entirely here.

https://github.com/brightlayer-ui/react-native-component-library/blob/e1a9d9fa756cf9a116247a5e9e3243a2c6a2d58b/components/src/core/mobile-stepper/mobile-stepper.tsx#L42

Should be:

```tsx
        filled: {
            backgroundColor: props.activeColor || theme.colors.primary,
        },
```

Comment (daileytj) [reply login-workflow/src/screens/InviteRegistrationPager.tsx:524]: That's a good call. You mentioned this before and I skipped over it. Will update accordingly.

**Comment by daileytj** [comment]
Converting this to a draft until we can get an alpha/beta publish of components v6.0.3

**Review by jeffvg — APPROVED** [review]
looks good iOS/android
